<a href="https://colab.research.google.com/github/ag6393163475-lab/Data_Science/blob/main/lect_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [2]:
import numpy as np
a=np.array([4,3,2,3,9])
print(a)

[4 3 2 3 9]


In [3]:
import numpy as np
a=np.array([4,3,2,3,9,'hello'])
print(a)

['4' '3' '2' '3' '9' 'hello']


In [4]:
#ques
np_array=np.array([3,4,6,9,'hello',False])
print(bool(np_array[-1]))

True


In [5]:
a=0
print(bool(a))

False


In [6]:
a='0'
print(bool(a))

True


In [7]:
import numpy as np

a = np.zeros((2, 3, 4), dtype=int)
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [9]:
import numpy as np

a = np.ones((2, 3, 4), dtype=int)
print(a)

print(type(a[0][0][0]))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.int64'>


In [11]:
import numpy as np

a = np.empty((2, 3, 4), dtype=int)
print(a)

# print(type(a[0][0][0]))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [12]:
import numpy as np

# full
a = np.full(4, 5, dtype=int)
print(a)


[5 5 5 5]


In [ ]:
import numpy as np
# arange
a = np.arange(0, 9, 2, dtype=int)
print(a)


In [13]:
import numpy as np
# linspace
a = np.linspace(3, 12, 4, dtype=int)
print(a)

[ 3  6  9 12]


In [17]:
import numpy as np
# Shape and Size of 1-D array
a = np.arange(0, 9, 2, dtype=int)
print(a.shape)
print(a.size)



(5,)
5


In [16]:
import numpy as np
# Shape and Size of 2-D array
a = np.ones((2, 3), dtype=int)
print(a.shape)
print(a.size)


(2, 3)
6


In [15]:
import numpy as np
# Random Number Generation
a = np.random.randint(0, 9, 2)
print(a)

[0 1]


In [14]:
import numpy as np
# Random Choice
a = np.random.choice([1, 7, 4], 2)
print(a)

[1 7]


In [18]:
import numpy as np

# Broadcasting

a = np.array([1, 2, 3, 4])

b = np.array([9, 3, 4, 6])

print(a * 2)
print(a + b)
print(a * b)
print(a / b)
print((2 * a) + b)

[2 4 6 8]
[10  5  7 10]
[ 9  6 12 24]
[0.11111111 0.66666667 0.75       0.66666667]
[11  7 10 14]


In [19]:
import numpy as np

# Concatenate in 1-D array

a = np.random.randint(2, 15, 6)
print(a)

b = np.random.randint(2, 15, 6)
print(b)

print(np.concatenate((a, b)))

[ 8  5 12 11  6  2]
[ 9  4  9  6  7 12]
[ 8  5 12 11  6  2  9  4  9  6  7 12]


In [21]:
import numpy as np

# Concatenate in 2-D array

a = np.random.randint(2, 15, (2, 3))
print(a)

b = np.random.randint(2, 15, (2, 3))
print(b)

print(np.concatenate((a, b), axis=0))  # Row-wise

print(np.concatenate((a, b), axis=1))  # Column-wise

[[11  8  2]
 [11  9 13]]
[[6 7 3]
 [8 2 2]]
[[11  8  2]
 [11  9 13]
 [ 6  7  3]
 [ 8  2  2]]
[[11  8  2  6  7  3]
 [11  9 13  8  2  2]]


In [22]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

b = np.random.randint(1, 15, 6)
print(b)

c = np.where(b > 2, b, a)
print(c)

[5 6 3 9 7 2]
[ 9  2  2  4  4 12]
[ 9  6  3  4  4 12]


In [23]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.sort(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.sort(b))

[13  6  3  8 12  3]
[ 3  3  6  8 12 13]
[ 4  5 13  6  5 13]
[ 4  5  5  6 13 13]


In [24]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.sum(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.sum(b))

[14  9  2 13  9 13]
60
[14 10 12  3  3 11]
53


In [25]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.mean(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.mean(b))

[10 14 14 10  3 10]
10.166666666666666
[13  7  2 13  7 14]
9.333333333333334


In [26]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.std(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.std(b))

[ 6  8  9 14 14  6]
3.3541019662496847
[7 5 3 4 2 9]
2.3804761428476167


In [27]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.min(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.max(b))

[ 7  5 14 13 11 14]
5
[ 2 10 11  3 10  6]
11


In [28]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

print(np.unique(a))

b = np.random.randint(2, 15, 6)
print(b)

print(np.unique(b))

[13  3  2  9  2  3]
[ 2  3  9 13]
[ 7  7  7  5 11 10]
[ 5  7 10 11]


In [29]:
import numpy as np

a = np.random.randint(2, 15, 6)
print(a)

c = a.reshape(2, 3)

b = np.random.randint(2, 15, 6)
print(b)

d = b.reshape(3, 2)

66print(np.matmul(c, d))

[ 4  7  2 14  4  8]
[ 6  4  3 13  5 11]
[[ 55 129]
 [136 196]]


In [ ]:
scores = []

days = []

for i in range(0, 7, 1):
    runs = input(np.array(()))